name: workflows

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.12.4
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.4"
      - name: Install dependencies with pip
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest numpy pandas
      - name: Lint with flake8
        run: |
          flake8 .
      - name: Test with pytest
        run: |
          pytest
